"""Migration safety: fresh installs, adopting pre-Alembic databases that hold
real Look data, downgrade/upgrade round trips, and model/migration drift.

Runs on SQLite always, and also on PostgreSQL when TEST_DATABASE_URL points
at a THROWAWAY database (CI does this). That database's public schema is
wiped at the start of every test here.
"""

import os
from datetime import date, datetime, time

import pytest
import sqlalchemy as sa
from alembic.util import AutogenerateDiffsDetected
from sqlmodel import Session, SQLModel

import app.models  # noqa: F401  (register every table)
from app import migrate as migrations
from app.models import Event, EventOverride, FoodEntry, NutritionTarget, RecurrenceRule, Task, User
from app.models.enums import MealType, RecurrencePattern, TaskPriority, TaskStatus

MODEL_TABLES = set(SQLModel.metadata.tables)
BASELINE_TABLES = set(migrations.baseline_schema())
CORE_TABLES = ["users", "recurrence_rules", "tasks"]

BACKENDS = [
    "sqlite",
    pytest.param(
        "postgres",
        marks=pytest.mark.skipif(
            not os.environ.get("TEST_DATABASE_URL"),
            reason="set TEST_DATABASE_URL to a throwaway PostgreSQL database to run these on Postgres",
        ),
    ),
]


@pytest.fixture(params=BACKENDS)
def db(request, tmp_path):
    if request.param == "sqlite":
        engine = sa.create_engine(f"sqlite:///{tmp_path / 'look.db'}")
    else:
        engine = sa.create_engine(os.environ["TEST_DATABASE_URL"])
        with engine.begin() as conn:
            conn.execute(sa.text("DROP SCHEMA public CASCADE"))
            conn.execute(sa.text("CREATE SCHEMA public"))
    yield engine
    engine.dispose()


# ---- realistic Look data --------------------------------------------------


def build_pre_alembic_db(engine, tables=None):
    """What every Look version before Alembic did at startup: create_all()
    over the models that existed then, i.e. the baseline's tables. (Models
    added later, like the LeetCode tables, never existed pre-Alembic.)"""
    names = tables or sorted(migrations.baseline_schema())
    SQLModel.metadata.create_all(engine, tables=[SQLModel.metadata.tables[t] for t in names])


def seed_core(session: Session) -> None:
    session.add(User(username="dhanush", password_hash="$2b$12$examplehash"))
    rule = RecurrenceRule(
        title="LeetCode daily", category="LeetCode", priority=TaskPriority.high,
        pattern=RecurrencePattern.daily, start_date=date(2026, 9, 1), tags=["dsa"],
    )
    session.add(rule)
    session.flush()
    session.add(Task(
        title="Two Sum", status=TaskStatus.completed, priority=TaskPriority.high, category="LeetCode",
        tags=["arrays", "hashmap"], due_date=date(2026, 9, 2), recurrence_rule_id=rule.id,
        occurrence_date=date(2026, 9, 2), completed_at=datetime(2026, 9, 2, 21, 15),
    ))
    session.add(Task(
        title="Problem set 3", status=TaskStatus.todo, priority=TaskPriority.critical, category="school",
        due_date=date(2026, 10, 3), due_time=time(23, 59), notes="chapter 4", planned_for_date=date(2026, 10, 2),
    ))


def seed_new_features(session: Session) -> None:
    event = Event(
        title="CS 101", category="class", location="Hall A",
        start_at=datetime(2026, 8, 24, 10, 0), end_at=datetime(2026, 8, 24, 10, 50),
        rrule="FREQ=WEEKLY;BYDAY=MO,WE,FR;UNTIL=20261212T235959", exdates=["2026-11-27"],
    )
    session.add(event)
    session.flush()
    session.add(EventOverride(event_id=event.id, original_date=date(2026, 8, 26), cancelled=True))
    session.add(FoodEntry(name="Greek yogurt", quantity="200 g", calories=150, protein_g=15,
                          meal=MealType.breakfast, eaten_on=date(2026, 10, 1)))
    session.add(NutritionTarget(calories=2400, protein_g=160, effective_from=date(2026, 10, 1)))


def add_legacy_recruiting_table(engine) -> None:
    """The table left behind (with a row) when recruiting tracking was
    removed; it isn't in the models any more and must never be dropped."""
    with engine.begin() as conn:
        conn.execute(sa.text(
            "CREATE TABLE recruiting_details (id VARCHAR PRIMARY KEY, "
            "task_id VARCHAR NOT NULL UNIQUE REFERENCES tasks(id), company VARCHAR)"
        ))
        task_id = conn.execute(sa.text("SELECT id FROM tasks ORDER BY title LIMIT 1")).scalar()
        conn.execute(sa.text("INSERT INTO recruiting_details VALUES ('r1', :t, 'Acme Robotics')"), {"t": task_id})


def snapshot(engine, tables=None):
    """Every row of every (given) model table, normalized for comparison."""
    insp = sa.inspect(engine)
    out = {}
    with engine.connect() as conn:
        for name in sorted(tables or MODEL_TABLES):
            if not insp.has_table(name):
                continue
            rows = conn.execute(sa.select(SQLModel.metadata.tables[name])).mappings().all()
            out[name] = sorted(repr(sorted(dict(r).items())) for r in rows)
    return out


def tables_in(engine):
    return set(sa.inspect(engine).get_table_names())


# ---- tests ---------------------------------------------------------------


def test_empty_database_migrates_to_head(db):
    assert migrations.migrate(db) == migrations.head_revision()
    assert MODEL_TABLES | {"alembic_version"} <= tables_in(db)


def test_migrated_schema_works_with_the_app(db):
    migrations.migrate(db)
    from app.services import events as events_svc
    from app.services import nutrition as nutrition_svc
    from app.services import tasks as tasks_svc

    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)
        session.commit()
        days = [o.occurrence_date for o in events_svc.occurrences(session, date(2026, 8, 24), date(2026, 8, 28))]
        assert days == [date(2026, 8, 24), date(2026, 8, 28)]  # the 26th is cancelled
        assert nutrition_svc.day_summary(session, date(2026, 10, 1)).remaining.protein_g == 145
        titles = {t.title for t in tasks_svc.list_tasks(session, include_completed=True)}
        assert titles == {"Two Sum", "Problem set 3"}


def test_pre_alembic_database_is_adopted_without_losing_data(db):
    build_pre_alembic_db(db)
    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)
        session.commit()
    add_legacy_recruiting_table(db)
    before = snapshot(db)

    assert migrations.migrate(db) == migrations.head_revision()

    assert snapshot(db, before.keys()) == before  # every pre-existing table unchanged
    with db.connect() as conn:
        assert conn.execute(sa.text("SELECT company FROM recruiting_details")).scalar() == "Acme Robotics"
    migrations.check_drift(db)  # schema now matches the models; legacy table ignored, not dropped
    assert "recruiting_details" in tables_in(db)


def test_older_pre_alembic_database_gets_the_tables_it_lacks(db):
    build_pre_alembic_db(db, tables=CORE_TABLES)  # an install from before events/nutrition existed
    with Session(db) as session:
        seed_core(session)
        session.commit()
    before = snapshot(db, CORE_TABLES)

    migrations.migrate(db)

    assert snapshot(db, CORE_TABLES) == before
    assert {"events", "event_overrides", "food_entries", "nutrition_targets"} <= tables_in(db)
    with Session(db) as session:
        seed_new_features(session)  # and the new tables are usable
        session.commit()
    migrations.check_drift(db)


def test_incompatible_pre_alembic_database_is_refused_and_left_untouched(db):
    build_pre_alembic_db(db, tables=CORE_TABLES)
    with Session(db) as session:
        seed_core(session)
        session.commit()
    with db.begin() as conn:
        conn.execute(sa.text("ALTER TABLE tasks DROP COLUMN notes"))
    before = snapshot(db, ["users", "recurrence_rules"])

    with pytest.raises(migrations.MigrationError, match="tasks: missing column"):
        migrations.migrate(db)

    assert "alembic_version" not in tables_in(db)
    assert "events" not in tables_in(db)
    assert snapshot(db, ["users", "recurrence_rules"]) == before


def test_running_migrate_again_is_a_noop(db):
    migrations.migrate(db)
    with Session(db) as session:
        seed_core(session)
        session.commit()
    before = snapshot(db)
    assert migrations.migrate(db) == migrations.head_revision()
    assert snapshot(db) == before


def test_downgrade_requires_explicit_flag_then_round_trips(db):
    migrations.migrate(db)
    with pytest.raises(RuntimeError, match="allow-data-loss"):
        migrations.downgrade(db, "base")
    # The baseline's guard stops it and the whole downgrade rolls back,
    # including 0002's step before it (on SQLite too).
    assert MODEL_TABLES <= tables_in(db)
    assert migrations.database_revision(db) == migrations.head_revision()

    migrations.downgrade(db, "base", allow_data_loss=True)
    assert not (MODEL_TABLES & tables_in(db))

    assert migrations.migrate(db) == migrations.head_revision()
    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)
        session.commit()


def test_models_and_migrations_have_not_drifted(db):
    migrations.migrate(db)
    migrations.check_drift(db)


def test_drift_check_catches_a_schema_mismatch(db):
    migrations.migrate(db)
    with db.begin() as conn:
        conn.execute(sa.text("DROP INDEX ix_tasks_status"))
    with pytest.raises(AutogenerateDiffsDetected):
        migrations.check_drift(db)


def test_app_refuses_an_unmigrated_database(db):
    with pytest.raises(migrations.MigrationError, match="python -m app.migrate"):
        migrations.assert_at_head(db)
    migrations.migrate(db)
    assert migrations.assert_at_head(db) == migrations.head_revision()


def test_migrate_command_exits_nonzero_so_containers_dont_start(tmp_path, monkeypatch):
    from app import db as db_module

    broken = sa.create_engine(f"sqlite:///{tmp_path / 'broken.db'}")
    build_pre_alembic_db(broken, tables=CORE_TABLES)
    with broken.begin() as conn:
        conn.execute(sa.text("ALTER TABLE tasks DROP COLUMN notes"))
    monkeypatch.setattr(db_module, "engine", broken)
    assert migrations.main() == 1

    fresh = sa.create_engine(f"sqlite:///{tmp_path / 'fresh.db'}")
    monkeypatch.setattr(db_module, "engine", fresh)
    assert migrations.main() == 0
    assert migrations.assert_at_head(fresh) == migrations.head_revision()


# ---- 0002: LeetCode tracking ------------------------------------------------

LEETCODE_TABLES = {"leetcode_problems", "leetcode_attempts", "leetcode_goals"}


def seed_leetcode(engine):
    from app.schemas import LeetCodeAttemptCreate
    from app.services import leetcode as leetcode_svc

    with Session(engine) as session:
        leetcode_svc.log_attempt(session, LeetCodeAttemptCreate(
            problem_number=560, title="Subarray Sum Equals K", difficulty="medium", topics=["Prefix Sum"],
            hint_used=True, duration_minutes=23, language="Java", confidence=3,
        ))


def test_leetcode_migration_is_additive_and_reversible(db):
    migrations.migrate(db)
    assert LEETCODE_TABLES <= tables_in(db)
    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)
        session.commit()
    others = snapshot(db, MODEL_TABLES - LEETCODE_TABLES)

    migrations.downgrade(db, "0001_baseline")  # no LeetCode data yet: allowed
    assert not (LEETCODE_TABLES & tables_in(db))
    assert snapshot(db, MODEL_TABLES - LEETCODE_TABLES) == others
    assert migrations.database_revision(db) == "0001_baseline"

    assert migrations.migrate(db) == migrations.head_revision()
    seed_leetcode(db)
    assert snapshot(db, MODEL_TABLES - LEETCODE_TABLES) == others
    migrations.check_drift(db)


def test_leetcode_downgrade_with_data_needs_explicit_flag(db):
    migrations.migrate(db)
    seed_leetcode(db)
    with Session(db) as session:
        seed_core(session)
        session.commit()
    others = snapshot(db, MODEL_TABLES - LEETCODE_TABLES)

    with pytest.raises(RuntimeError, match="allow-data-loss"):
        migrations.downgrade(db, "0001_baseline")
    assert LEETCODE_TABLES <= tables_in(db)

    migrations.downgrade(db, "0001_baseline", allow_data_loss=True)
    assert not (LEETCODE_TABLES & tables_in(db))
    assert snapshot(db, MODEL_TABLES - LEETCODE_TABLES) == others
