"""Migration safety: fresh installs, adopting pre-Alembic databases that hold
real Look data, downgrade/upgrade round trips, and model/migration drift.

Runs on SQLite always, and also on PostgreSQL when TEST_DATABASE_URL points
at a THROWAWAY database (CI does this). That database's public schema is
wiped at the start of every test here.
"""

import os
from datetime import date, datetime, time

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.util import AutogenerateDiffsDetected
from sqlmodel import Session, SQLModel

import app.models  # noqa: F401  (register every table)
from app import migrate as migrations
from app.models import Event, EventOverride, FoodEntry, NutritionTarget, RecurrenceRule, Task, User
from app.models.enums import MealType, RecurrencePattern, TaskPriority, TaskStatus

MODEL_TABLES = set(SQLModel.metadata.tables)
BASELINE_TABLES = set(migrations.baseline_schema())
CORE_TABLES = ["users", "recurrence_rules", "tasks"]

BACKENDS = [
    "sqlite",
    pytest.param(
        "postgres",
        marks=pytest.mark.skipif(
            not os.environ.get("TEST_DATABASE_URL"),
            reason="set TEST_DATABASE_URL to a throwaway PostgreSQL database to run these on Postgres",
        ),
    ),
]


@pytest.fixture(params=BACKENDS)
def db(request, tmp_path):
    if request.param == "sqlite":
        engine = sa.create_engine(f"sqlite:///{tmp_path / 'look.db'}")
    else:
        engine = sa.create_engine(os.environ["TEST_DATABASE_URL"])
        with engine.begin() as conn:
            conn.execute(sa.text("DROP SCHEMA public CASCADE"))
            conn.execute(sa.text("CREATE SCHEMA public"))
    yield engine
    engine.dispose()


# ---- realistic Look data --------------------------------------------------


def build_pre_alembic_db(engine, tables=None):
    """What every Look version before Alembic did at startup: create_all()
    over the models as they were then, i.e. the baseline's tables and
    columns (not today's models: later columns like events.subscription_id
    and tables like the LeetCode ones never existed pre-Alembic). Built by
    running the baseline and then forgetting Alembic was involved."""
    names = set(tables or migrations.baseline_schema())
    with engine.begin() as conn:
        command.upgrade(migrations.alembic_config(conn), migrations.BASELINE_REVISION)
        for table in reversed(SQLModel.metadata.sorted_tables):
            if table.name in BASELINE_TABLES and table.name not in names:
                conn.execute(sa.text(f"DROP TABLE {table.name}"))
        conn.execute(sa.text("DROP TABLE alembic_version"))


def seed_core(session: Session) -> None:
    session.add(User(username="dhanush", password_hash="$2b$12$examplehash"))
    rule = RecurrenceRule(
        title="LeetCode daily", category="LeetCode", priority=TaskPriority.high,
        pattern=RecurrencePattern.daily, start_date=date(2026, 9, 1), tags=["dsa"],
    )
    session.add(rule)
    session.flush()
    session.add(Task(
        title="Two Sum", status=TaskStatus.completed, priority=TaskPriority.high, category="LeetCode",
        tags=["arrays", "hashmap"], due_date=date(2026, 9, 2), recurrence_rule_id=rule.id,
        occurrence_date=date(2026, 9, 2), completed_at=datetime(2026, 9, 2, 21, 15),
    ))
    session.add(Task(
        title="Problem set 3", status=TaskStatus.todo, priority=TaskPriority.critical, category="school",
        due_date=date(2026, 10, 3), due_time=time(23, 59), notes="chapter 4", planned_for_date=date(2026, 10, 2),
    ))


def seed_new_features(session: Session) -> None:
    # Core insert into the events table as the database has it (reflected),
    # so this also seeds databases at older revisions that lack later columns.
    event_id = "evt-cs101"
    events = sa.Table("events", sa.MetaData(), autoload_with=session.connection())
    session.execute(sa.insert(events).values(
        id=event_id, title="CS 101", category="social", location="Hall A", notes=None, all_day=False,
        start_at=datetime(2026, 8, 24, 10, 0), end_at=datetime(2026, 8, 24, 10, 50),
        rrule="FREQ=WEEKLY;BYDAY=MO,WE,FR;UNTIL=20261212T235959", exdates=["2026-11-27"], source="manual",
        created_at=datetime(2026, 8, 20, 9, 0), updated_at=datetime(2026, 8, 20, 9, 0),
    ))
    session.add(EventOverride(event_id=event_id, original_date=date(2026, 8, 26), cancelled=True))
    session.add(FoodEntry(name="Greek yogurt", quantity="200 g", calories=150, protein_g=15,
                          meal=MealType.breakfast, eaten_on=date(2026, 10, 1)))
    session.add(NutritionTarget(calories=2400, protein_g=160, effective_from=date(2026, 10, 1)))


def add_legacy_recruiting_table(engine) -> None:
    """The table left behind (with a row) when recruiting tracking was
    removed; it isn't in the models any more and must never be dropped."""
    with engine.begin() as conn:
        conn.execute(sa.text(
            "CREATE TABLE recruiting_details (id VARCHAR PRIMARY KEY, "
            "task_id VARCHAR NOT NULL UNIQUE REFERENCES tasks(id), company VARCHAR)"
        ))
        task_id = conn.execute(sa.text("SELECT id FROM tasks ORDER BY title LIMIT 1")).scalar()
        conn.execute(sa.text("INSERT INTO recruiting_details VALUES ('r1', :t, 'Acme Robotics')"), {"t": task_id})


def snapshot(engine, tables=None):
    """Every row of every (given) model table, normalized for comparison.
    Only columns the database has at its current revision are read, and
    null and false values are left out, so a row compares equal across a
    revision that only added nullable or default-false columns."""
    insp = sa.inspect(engine)
    out = {}
    with engine.connect() as conn:
        for name in sorted(tables or MODEL_TABLES):
            if not insp.has_table(name):
                continue
            model = SQLModel.metadata.tables[name]
            present = [model.c[c["name"]] for c in insp.get_columns(name) if c["name"] in model.c]
            rows = conn.execute(sa.select(*present)).mappings().all()
            out[name] = sorted(
                repr(sorted((k, v) for k, v in dict(r).items() if v is not None and v is not False)) for r in rows
            )
    return out


def tables_in(engine):
    return set(sa.inspect(engine).get_table_names())


# ---- tests ---------------------------------------------------------------


def test_empty_database_migrates_to_head(db):
    assert migrations.migrate(db) == migrations.head_revision()
    assert MODEL_TABLES | {"alembic_version"} <= tables_in(db)


def test_migrated_schema_works_with_the_app(db):
    migrations.migrate(db)
    from app.services import events as events_svc
    from app.services import nutrition as nutrition_svc
    from app.services import tasks as tasks_svc

    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)
        session.commit()
        days = [o.occurrence_date for o in events_svc.occurrences(session, date(2026, 8, 24), date(2026, 8, 28))]
        assert days == [date(2026, 8, 24), date(2026, 8, 28)]  # the 26th is cancelled
        assert nutrition_svc.day_summary(session, date(2026, 10, 1)).remaining.protein_g == 145
        titles = {t.title for t in tasks_svc.list_tasks(session, include_completed=True)}
        assert titles == {"Two Sum", "Problem set 3"}


def test_pre_alembic_database_is_adopted_without_losing_data(db):
    build_pre_alembic_db(db)
    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)
        session.commit()
    add_legacy_recruiting_table(db)
    before = snapshot(db)

    assert migrations.migrate(db) == migrations.head_revision()

    assert snapshot(db, before.keys()) == before  # every pre-existing table unchanged
    with db.connect() as conn:
        assert conn.execute(sa.text("SELECT company FROM recruiting_details")).scalar() == "Acme Robotics"
    migrations.check_drift(db)  # schema now matches the models; legacy table ignored, not dropped
    assert "recruiting_details" in tables_in(db)


def test_older_pre_alembic_database_gets_the_tables_it_lacks(db):
    build_pre_alembic_db(db, tables=CORE_TABLES)  # an install from before events/nutrition existed
    with Session(db) as session:
        seed_core(session)
        session.commit()
    before = snapshot(db, CORE_TABLES)

    migrations.migrate(db)

    assert snapshot(db, CORE_TABLES) == before
    assert {"events", "event_overrides", "food_entries", "nutrition_targets"} <= tables_in(db)
    with Session(db) as session:
        seed_new_features(session)  # and the new tables are usable
        session.commit()
    migrations.check_drift(db)


def test_incompatible_pre_alembic_database_is_refused_and_left_untouched(db):
    build_pre_alembic_db(db, tables=CORE_TABLES)
    with Session(db) as session:
        seed_core(session)
        session.commit()
    with db.begin() as conn:
        conn.execute(sa.text("ALTER TABLE tasks DROP COLUMN notes"))
    before = snapshot(db, ["users", "recurrence_rules"])

    with pytest.raises(migrations.MigrationError, match="tasks: missing column"):
        migrations.migrate(db)

    assert "alembic_version" not in tables_in(db)
    assert "events" not in tables_in(db)
    assert snapshot(db, ["users", "recurrence_rules"]) == before


def test_running_migrate_again_is_a_noop(db):
    migrations.migrate(db)
    with Session(db) as session:
        seed_core(session)
        session.commit()
    before = snapshot(db)
    assert migrations.migrate(db) == migrations.head_revision()
    assert snapshot(db) == before


def test_downgrade_requires_explicit_flag_then_round_trips(db):
    migrations.migrate(db)
    with pytest.raises(RuntimeError, match="allow-data-loss"):
        migrations.downgrade(db, "base")
    # The baseline's guard stops it and the whole downgrade rolls back,
    # including 0002's step before it (on SQLite too).
    assert MODEL_TABLES <= tables_in(db)
    assert migrations.database_revision(db) == migrations.head_revision()

    migrations.downgrade(db, "base", allow_data_loss=True)
    assert not (MODEL_TABLES & tables_in(db))

    assert migrations.migrate(db) == migrations.head_revision()
    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)
        session.commit()


def test_models_and_migrations_have_not_drifted(db):
    migrations.migrate(db)
    migrations.check_drift(db)


def test_drift_check_catches_a_schema_mismatch(db):
    migrations.migrate(db)
    with db.begin() as conn:
        conn.execute(sa.text("DROP INDEX ix_tasks_status"))
    with pytest.raises(AutogenerateDiffsDetected):
        migrations.check_drift(db)


def test_app_refuses_an_unmigrated_database(db):
    with pytest.raises(migrations.MigrationError, match="python -m app.migrate"):
        migrations.assert_at_head(db)
    migrations.migrate(db)
    assert migrations.assert_at_head(db) == migrations.head_revision()


def test_migrate_command_exits_nonzero_so_containers_dont_start(tmp_path, monkeypatch):
    from app import db as db_module

    broken = sa.create_engine(f"sqlite:///{tmp_path / 'broken.db'}")
    build_pre_alembic_db(broken, tables=CORE_TABLES)
    with broken.begin() as conn:
        conn.execute(sa.text("ALTER TABLE tasks DROP COLUMN notes"))
    monkeypatch.setattr(db_module, "engine", broken)
    assert migrations.main() == 1

    fresh = sa.create_engine(f"sqlite:///{tmp_path / 'fresh.db'}")
    monkeypatch.setattr(db_module, "engine", fresh)
    assert migrations.main() == 0
    assert migrations.assert_at_head(fresh) == migrations.head_revision()


# ---- 0002: LeetCode tracking ------------------------------------------------

LEETCODE_TABLES = {"leetcode_problems", "leetcode_attempts", "leetcode_goals"}


def seed_leetcode(engine):
    from app.schemas import LeetCodeAttemptCreate
    from app.services import leetcode as leetcode_svc

    with Session(engine) as session:
        leetcode_svc.log_attempt(session, LeetCodeAttemptCreate(
            problem_number=560, title="Subarray Sum Equals K", difficulty="medium", topics=["Prefix Sum"],
            hint_used=True, duration_minutes=23, language="Java", confidence=3,
        ))


def test_leetcode_migration_is_additive_and_reversible(db):
    migrations.migrate(db)
    assert LEETCODE_TABLES <= tables_in(db)
    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)
        session.commit()
    others = snapshot(db, BASELINE_TABLES)

    migrations.downgrade(db, "0001_baseline")  # no LeetCode data yet: allowed
    assert not (LEETCODE_TABLES & tables_in(db))
    assert snapshot(db, BASELINE_TABLES) == others
    assert migrations.database_revision(db) == "0001_baseline"

    assert migrations.migrate(db) == migrations.head_revision()
    seed_leetcode(db)
    assert snapshot(db, BASELINE_TABLES) == others
    migrations.check_drift(db)


def test_leetcode_downgrade_with_data_needs_explicit_flag(db):
    migrations.migrate(db)
    seed_leetcode(db)
    with Session(db) as session:
        seed_core(session)
        session.commit()
    others = snapshot(db, BASELINE_TABLES)

    with pytest.raises(RuntimeError, match="allow-data-loss"):
        migrations.downgrade(db, "0001_baseline")
    assert LEETCODE_TABLES <= tables_in(db)

    migrations.downgrade(db, "0001_baseline", allow_data_loss=True)
    assert not (LEETCODE_TABLES & tables_in(db))
    assert snapshot(db, BASELINE_TABLES) == others


# ---- 0003: calendar subscriptions -----------------------------------------


def test_calendar_subscription_migration_keeps_existing_events(db):
    with db.begin() as conn:
        command.upgrade(migrations.alembic_config(conn), "0002_add_leetcode_tracking")
    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)  # a manual recurring event with an override
        session.commit()
    before = snapshot(db, BASELINE_TABLES)

    assert migrations.migrate(db) == migrations.head_revision()
    assert snapshot(db, BASELINE_TABLES) == before  # new event columns are all null
    with db.connect() as conn:
        assert conn.execute(sa.text("SELECT COUNT(*) FROM events WHERE subscription_id IS NULL")).scalar() == 1
    migrations.check_drift(db)

    migrations.downgrade(db, "0002_add_leetcode_tracking")  # no subscriptions: allowed
    assert "calendar_subscriptions" not in tables_in(db)
    assert snapshot(db, BASELINE_TABLES) == before
    assert migrations.migrate(db) == migrations.head_revision()


def test_calendar_downgrade_with_subscriptions_needs_explicit_flag(db):
    from app.models import CalendarSubscription
    from app.models.enums import CalendarSourceType

    migrations.migrate(db)
    with Session(db) as session:
        session.add(CalendarSubscription(name="Canvas", source_type=CalendarSourceType.url,
                                         source_url="https://canvas.example.edu/feeds/calendars/user_x.ics"))
        session.commit()
    with pytest.raises(RuntimeError, match="allow-data-loss"):
        migrations.downgrade(db, "0002_add_leetcode_tracking")
    assert "calendar_subscriptions" in tables_in(db)
    migrations.downgrade(db, "0002_add_leetcode_tracking", allow_data_loss=True)
    assert "calendar_subscriptions" not in tables_in(db)


# ---- 0004: deadline completion --------------------------------------------


def test_deadline_completion_migration_is_additive(db):
    with db.begin() as conn:
        command.upgrade(migrations.alembic_config(conn), "0003_calendar_subscriptions")
    with Session(db) as session:
        seed_core(session)
        seed_new_features(session)
        session.commit()
    before = snapshot(db, BASELINE_TABLES)

    with db.begin() as conn:
        command.upgrade(migrations.alembic_config(conn), "0004_event_deadline_completion")
    assert snapshot(db, BASELINE_TABLES) == before
    with db.connect() as conn:
        row = conn.execute(sa.text(
            "SELECT is_deadline, completed_at, completion_source, external_completed FROM events"
        )).one()
    assert (bool(row[0]), row[1], row[2], row[3]) == (False, None, None, None)

    migrations.downgrade(db, "0003_calendar_subscriptions")  # nothing checked off: allowed
    cols = {c["name"] for c in sa.inspect(db).get_columns("events")}
    assert not cols & {"is_deadline", "completed_at", "completion_source", "external_completed"}
    assert "subscription_id" in cols  # 0003's columns untouched
    assert snapshot(db, BASELINE_TABLES) == before


def test_deadline_downgrade_with_checkmarks_needs_explicit_flag(db):
    migrations.migrate(db)
    with Session(db) as session:
        seed_new_features(session)
        session.commit()
    with db.begin() as conn:
        conn.execute(sa.text("UPDATE events SET is_deadline = true, completed_at = CURRENT_TIMESTAMP"))
    with pytest.raises(RuntimeError, match="allow-data-loss"):
        migrations.downgrade(db, "0003_calendar_subscriptions")
    migrations.downgrade(db, "0003_calendar_subscriptions", allow_data_loss=True)
    assert "completed_at" not in {c["name"] for c in sa.inspect(db).get_columns("events")}



# ---- 0005: courses and categories -----------------------------------------


def test_courses_and_categories_migration_preserves_and_seeds(db):
    with db.begin() as conn:
        command.upgrade(migrations.alembic_config(conn), "0004_event_deadline_completion")
    with Session(db) as session:
        seed_core(session)  # categories "LeetCode" and "school"
        seed_new_features(session)  # event category "social"
        session.commit()
    with db.begin() as conn:  # a category nobody predefined, and a completed import
        conn.execute(sa.text("UPDATE tasks SET category = 'VT Hacks' WHERE title = 'Two Sum'"))
        conn.execute(sa.text("UPDATE events SET is_deadline = true, completed_at = CURRENT_TIMESTAMP, completion_source = 'local'"))
    before = snapshot(db, BASELINE_TABLES)

    with db.begin() as conn:
        command.upgrade(migrations.alembic_config(conn), "0005_courses_and_categories")
    assert snapshot(db, BASELINE_TABLES) == before  # every task and event untouched
    with db.connect() as conn:
        cats = {r[0]: (r[1], r[2], bool(r[3])) for r in conn.execute(sa.text("SELECT key, name, color, is_system FROM categories"))}
        done = conn.execute(sa.text("SELECT completed_at IS NOT NULL, completion_source FROM events")).one()
    assert cats["school"] == ("School", "red", True) and cats["class"] == ("Class", "amber", True)
    assert cats["VT Hacks"][2] is False  # existing custom string adopted, not lost
    assert {"personal", "LeetCode", "errands", "project", "social", "sports", "work", "appointment", "other"} <= cats.keys()
    assert done == (True, "local")  # completed assignments stay completed

    migrations.downgrade(db, "0004_event_deadline_completion")  # nothing customized: allowed
    assert not {"categories", "courses", "course_links"} & tables_in(db)
    assert snapshot(db, BASELINE_TABLES) == before


def test_courses_downgrade_with_courses_needs_explicit_flag(db):
    migrations.migrate(db)
    with db.begin() as conn:
        conn.execute(sa.text(
            "INSERT INTO courses (id, code, code_key, color, style, aliases, archived, created_at, updated_at) "
            "VALUES ('c1', 'CS 3214', 'CS3214', 'blue', 'soft', '[]', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
        ))
    with pytest.raises(RuntimeError, match="allow-data-loss"):
        migrations.downgrade(db, "0004_event_deadline_completion")
    migrations.downgrade(db, "0004_event_deadline_completion", allow_data_loss=True)
    assert "courses" not in tables_in(db)
# ---- leetcode import metadata ---------------------------------------------

OLD_IMPORT_NOTE = (
    "Imported from Ddundee/lc-solutions submission_history.json. Accepted LeetCode submission {sid}: "
    "https://leetcode.com/submissions/detail/{sid}/. Original timestamp: 2026-10-01T05:41:09.000Z. "
    "Hint usage and independent solving are UNKNOWN (false fields are placeholders, not assessments); "
    "solve duration and confidence not recorded."
)


def test_leetcode_import_notes_are_cleaned_and_unknowns_restored(db):
    with db.begin() as conn:
        command.upgrade(migrations.alembic_config(conn), "0005_courses_and_categories")
    rows = [
        ("a1", OLD_IMPORT_NOTE.format(sid="111"), "mcp"),  # pure boilerplate
        ("a2", OLD_IMPORT_NOTE.format(sid="222") + " Off-by-one on the window again.", "mcp"),  # + user words
        ("a3", "Took 3 tries. Imported from Ddundee/lc-solutions submission_history.json. later", "manual"),  # not a prefix
        ("a4", "Solid. Used two pointers.", "manual"),  # unrelated
        ("a5", OLD_IMPORT_NOTE.format(sid="111"), "mcp"),  # the same submission imported twice
        ("a6", None, "manual"),
    ]
    with db.begin() as conn:
        conn.execute(sa.text(
            "INSERT INTO leetcode_problems (id, number, title, difficulty, topics, created_at, updated_at) "
            "VALUES ('p1', 560, 'Subarray Sum Equals K', 'medium', '[]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
        ))
        for aid, notes, source in rows:
            conn.execute(sa.text(
                "INSERT INTO leetcode_attempts (id, problem_id, attempted_at, solved, solved_independently, hint_used, "
                "notes, source, created_at) VALUES (:id, 'p1', CURRENT_TIMESTAMP, true, :ind, false, :notes, :source, "
                "CURRENT_TIMESTAMP)"
            ), {"id": aid, "notes": notes, "source": source, "ind": source == "manual"})

    assert migrations.migrate(db) == migrations.head_revision()
    with db.connect() as conn:
        got = {r[0]: r[1:] for r in conn.execute(sa.text(
            "SELECT id, notes, source, external_id, hint_used, solved_independently FROM leetcode_attempts"
        ))}
    norm = lambda r: (r[0], r[1], r[2], None if r[3] is None else bool(r[3]), None if r[4] is None else bool(r[4]))  # noqa: E731
    assert norm(got["a1"]) == (None, "leetcode", "111", None, None)
    assert norm(got["a2"]) == ("Off-by-one on the window again.", "leetcode", "222", None, None)
    assert norm(got["a3"]) == (rows[2][1], "manual", None, False, True)  # untouched
    assert norm(got["a4"]) == ("Solid. Used two pointers.", "manual", None, False, True)
    assert norm(got["a5"]) == (None, "mcp", None, None, None)  # cleaned; id already taken by a1
    assert norm(got["a6"]) == (None, "manual", None, False, True)
    migrations.check_drift(db)

    with pytest.raises(RuntimeError, match="allow-data-loss"):
        migrations.downgrade(db, "0005_courses_and_categories")
    migrations.downgrade(db, "0005_courses_and_categories", allow_data_loss=True)
    with db.connect() as conn:
        assert conn.execute(sa.text("SELECT COUNT(*) FROM leetcode_attempts WHERE hint_used IS NULL")).scalar() == 0



# ---- 0007: category life areas ---------------------------------------------


def _categories(db):
    with db.connect() as conn:
        return {r[0]: (r[1], r[2], r[3], bool(r[4])) for r in conn.execute(sa.text(
            "SELECT key, name, color, style, archived FROM categories"
        ))}


def test_category_life_areas_reorganize_untouched_defaults_only(db):
    with db.begin() as conn:
        command.upgrade(migrations.alembic_config(conn), "0006_leetcode_import_metadata")
        conn.execute(sa.text(
            "INSERT INTO events (id, title, category, all_day, start_at, end_at, exdates, source, created_at, updated_at, "
            "is_deadline) VALUES ('e1', 'CS 101', 'class', false, '2026-10-05 09:00:00', '2026-10-05 10:00:00', '[]', "
            "'manual', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false), "
            "('e2', 'Pickup game', 'sports', false, '2026-10-06 18:00:00', '2026-10-06 19:00:00', '[]', 'manual', "
            "CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, false)"
        ))
        # The user restyled Errands; a custom category exists.
        conn.execute(sa.text("UPDATE categories SET color = 'red', updated_at = CURRENT_TIMESTAMP WHERE key = 'errands'"))
        conn.execute(sa.text(
            "INSERT INTO categories (id, key, name, color, style, is_system, archived, created_at, updated_at) "
            "VALUES ('c-oa', 'OA', 'OA', 'cyan', 'solid', false, false, '2026-09-01', '2026-09-01')"
        ))

    assert migrations.migrate(db) == migrations.head_revision()
    cats = _categories(db)
    assert cats["work"] == ("Career", "violet", "soft", False)  # renamed by name; key unchanged
    assert cats["project"] == ("Projects", "teal", "outline", False)
    assert cats["organizations"][0] == "Organizations" and cats["health"][0] == "Health"
    assert cats["errands"] == ("Errands", "red", "solid", False)  # customized: untouched
    assert cats["OA"] == ("OA", "cyan", "solid", False)  # user category: untouched
    assert cats["class"][3] is True and cats["appointment"][3] is True  # merged / unused: archived
    assert cats["sports"][3] is False  # used by an event: left alone
    with db.connect() as conn:
        assert conn.execute(sa.text("SELECT category FROM events WHERE id = 'e1'")).scalar() == "school"
        assert conn.execute(sa.text("SELECT category FROM events WHERE id = 'e2'")).scalar() == "sports"
    migrations.check_drift(db)

    migrations.downgrade(db, "0006_leetcode_import_metadata")
    cats = _categories(db)
    assert cats["work"] == ("Work", "violet", "solid", False) and cats["class"][3] is False
    assert "organizations" not in cats and cats["errands"] == ("Errands", "red", "solid", False)
